trigger:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  GITHUB_REPO: 'https://github.com/sheetalpawashe/AZURE_DEPLOYMENT.git'
  GITHUB_USER: 'sheetalpawashe'

steps:
- script: |
    echo "Triggering branch: $(Build.SourceBranch)"
    BRANCH_NAME=$(Build.SourceBranchName)
    echo "Extracted Branch Name: ${BRANCH_NAME}"

    # Configure Git user information
    git config --global user.name $(GITHUB_USER)
    
    # Clone the specific branch from the Azure DevOps repository
    echo "Cloning the branch ${BRANCH_NAME} from Azure DevOps"
    git clone --branch ${BRANCH_NAME} --single-branch https://$(AZURE_DEVOPS_PAT)@dev.azure.com/sheetalchatur/AZURE_DEPLOYMENT/_git/AZURE_DEPLOYMENT
    cd AZURE_DEPLOYMENT

    # Verify the current branch
    echo "Current branch:"
    git branch -vv

    # Add GitHub as a remote
    echo "Adding GitHub as a remote"
    git remote add github https://$(GITHUB_USER):$(GITHUB_TOKEN)@github.com/sheetalpawashe/AZURE_DEPLOYMENT.git

    # Verify remotes
    echo "Remotes after adding GitHub:"
    git remote -v

    # Fetch the specific branch from GitHub to ensure it's up-to-date
    echo "Fetching the branch ${BRANCH_NAME} from GitHub"
    git fetch github ${BRANCH_NAME}

    # Push the specific branch to GitHub
    echo "Pushing the branch ${BRANCH_NAME} to GitHub"
    git push github ${BRANCH_NAME}:${BRANCH_NAME}

    echo "Finished pushing the branch: ${BRANCH_NAME}"

    # List branches on GitHub for verification
    echo "Listing branches on GitHub:"
    git ls-remote --heads github
  displayName: 'Sync Branch with GitHub'
  env:
    AZURE_DEVOPS_PAT: $(AZURE_DEVOPS_PAT)
    GITHUB_TOKEN: $(GITHUB_TOKEN)
